name: Build and tests

on:
  push:
    branches: [ master, develop, main]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:

########################################################################################
  make:
    name: Make
    strategy:
      fail-fast: false
      matrix:
        machine: [ubuntu-latest]
        gmake_install_command: ['gmake --version']
        include:
        - {machine: macOS-13, gmake_install_command: 'brew install make && gmake --version'}
    runs-on: ['${{ matrix.machine }}']   
   
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: install gmake
      run: ${{ matrix.gmake_install_command }}        
    - name: make
      run: | 
        gmake -j CXX=g++-12 CC=gcc-12 STATIC_LINK=true

    - name: tar artifacts
      run: tar -cvf lz-ani.tar ./test -C ./bin lz-ani
    
    - uses: actions/upload-artifact@v4
      with:
        name: executable-artifact-${{ matrix.machine }}
        path: ./lz-ani.tar    

########################################################################################
  vir61:
    needs: make
    name: Virus data
    strategy:
      fail-fast: false
      matrix:
        machine: [ubuntu-latest, macOS-13]
    runs-on: ['${{ matrix.machine }}']
    
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: executable-artifact-${{ matrix.machine }}
        path: ./
        
    - name: untar artifacts
      run: |
        tar -xf lz-ani.tar
    
    - name: build 
      run: |
        ./lz-ani all2all --in-dir ./test/vir61 --out ani.tsv
        cmp ani.tsv ./test/vir61.ani.tsv

