name: Self-hosted CI

on:
  pull_request:
    branches: [ master, develop, main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:

 ########################################################################################
  checkout:
    name: Checkout
    strategy:
      matrix:
        machine: [x64_linux, x64_mac, arm64_linux, arm64_mac]
    runs-on: [self-hosted, lz-ani, '${{ matrix.machine }}']
    
    steps:
    - name: clean
      run: rm -rf ${{ github.workspace }}/*
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    
########################################################################################
  make:
    name: Make
    needs: checkout
    strategy:
      fail-fast: false
      matrix:
        machine: [x64_linux, x64_mac, arm64_linux, arm64_mac]
        compiler: [11, 12, 13]
        include:
        - {machine: x64_linux, platform: avx2, compiler: 14}
        - {machine: x64_linux, platform: avx2}
        - {machine: arm64_linux, platform: arm8}
        - {machine: x64_mac, platform: avx2}
        - {machine: arm64_mac, platform: m1}
        exclude:
        - {machine: arm64_linux, compiler: 13}
        
    runs-on: [self-hosted, lz-ani, '${{ matrix.machine }}']  
        
    steps:
    - name: make
      run: | 
        gmake -j32 CXX=g++-${{matrix.compiler}} CC=gcc-${{matrix.compiler}} PLATFORM=${{ matrix.platform }} STATIC_LINK=true
        cp ./bin/lz-ani ./lz-ani-${{matrix.compiler}}
        gmake clean
        
########################################################################################
  help:
    name: Print usage
    needs: make
    strategy:
      fail-fast: false
      matrix:
        machine: [x64_linux, x64_mac, arm64_linux, arm64_mac]
        compiler: [11, 12, 13]
        include:
        - {machine: x64_linux, platform: avx2, compiler: 14}
        exclude:
        - {machine: arm64_linux, compiler: 13}
        
    runs-on: [self-hosted, lz-ani, '${{ matrix.machine }}']
    
    env: 
      EXEC: ./lz-ani-${{matrix.compiler}}
        
    steps:
    - name: help
      run: ${EXEC} 
    - name: version
      run: ${EXEC} -version  

 ########################################################################################
  vir61:
    name: Vir61
    needs: help
    strategy:
      fail-fast: false
      matrix:
        machine: [x64_linux, x64_mac, arm64_linux, arm64_mac]
        compiler: [11, 12, 13]
        include:
        - {machine: x64_linux, platform: avx2, compiler: 14}
        exclude:
        - {machine: arm64_linux, compiler: 13}
          
    runs-on: [self-hosted, lz-ani, '${{ matrix.machine }}']

    env: 
      EXEC: ./lz-ani-${{matrix.compiler}}
        
    steps:
          
    - name: all2all 
      run: |
        ${EXEC} all2all --in-dir ./test/vir61 --out ani.tsv
        cmp ani.tsv ./test/vir61.ani.tsv
