name: Self-hosted CI

on:
  pull_request:
    branches: [ master, develop, main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:

 ########################################################################################
  checkout:
    name: Checkout
    strategy:
      matrix:
        machine: [x64_linux, x64_mac, arm64_linux, arm64_mac]
    runs-on: [self-hosted, lz-ani, '${{ matrix.machine }}']
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    
########################################################################################
  make:
    name: Make
    needs: checkout
    strategy:
      fail-fast: false
      matrix:
        machine: [x64_linux, x64_mac, arm64_linux, arm64_mac]
        compiler: [g++-11, g++-12, g++-13]
        include:
        - machine: x64_linux
          platform: avx2
        - machine: arm64_linux
          platform: arm8
        - machine: x64_mac
          platform: avx2
        - machine: arm64_mac
          platform: m1
        exclude:
        - machine: arm64_linux
          compiler: g++-13
        
    runs-on: [self-hosted, lz-ani, '${{ matrix.machine }}']  
        
    steps:
    - name: make
      run: | 
        make -j32 CXX=${{matrix.compiler}} PLATFORM=${{ matrix.platform }}
        cp ./lz-ani ./lz-ani-${{matrix.compiler}}
        make clean
        
########################################################################################
  help:
    name: Print usage
    needs: make
    strategy:
      fail-fast: false
      matrix:
        machine: [x64_linux, x64_mac, arm64_linux, arm64_mac]
        compiler: [g++-11, g++-12, g++-13]
        exclude:
        - machine: arm64_linux
          compiler: g++-13
        
    runs-on: [self-hosted, lz-ani, '${{ matrix.machine }}']
    
    env: 
      EXEC: ./lz-ani-${{matrix.compiler}}
        
    steps:
    - name: help
      run: | 
       ${EXEC} 


 ########################################################################################
  vir61:
    name: Vir61
    needs: help
    strategy:
      fail-fast: false
      matrix:
        machine: [x64_linux, x64_mac, arm64_linux, arm64_mac]
        compiler: [g++-11, g++-12, g++-13]
        exclude:
        - machine: arm64_linux
          compiler: g++-13
          
    runs-on: [self-hosted, lz-ani, '${{ matrix.machine }}']

    env: 
      EXEC: ./lz-ani-${{matrix.compiler}}
        
    steps:
          
    - name: all2all 
      run: |
        ${EXEC} all2all --in-dir ./test/vir61 --out ani.tsv
        cmp ani.tsv ./test/vir61.ani.tsv
